FROM node:18

WORKDIR /app

COPY package.json tsconfig.json vite.config.ts esbuild.config.js ./
# COPY ../shared/certs ./certs
COPY public ./public
COPY src ./src

RUN npm install


EXPOSE 8081


CMD ["npm", "run", "dev"]

