services:
  server:
    container_name: nginx_frontend
    user: "0:0"
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "7000:7000"
    volumes:
      - ./shared/certs:/app/certs:ro
    networks:
      - transcendence-network
    restart: always
    depends_on:
      api-gateway:
        condition: service_started
