# services:
#   frontend:
#     build: ./
#     ports:
#       - "8080:80"
#     restart: always
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
services:
  frontend:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8081"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/8081"]
      interval: 30s
      timeout: 10s
      retries: 3
