# services:
#   frontend:
#     build: ./
#     ports:
#       - "8080:80"
#     restart: always
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
services:
  builder:
    container_name: builder
    build: 
      context: ./
      dockerfile: Dockerfile
      target: builder
    ports:
      - "7070:7070"
    volumes:
      - ./src:/app/src:ro
      - /app/node_modules
      - public:/app/public
    networks:
      - one
    restart: always
  server:
    container_name: nginx
    build: 
      context: ./
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "7000:7000"
    volumes:
      - ../shared/certs:/app/certs:ro
      - public:/app/public:ro
    networks:
      - one
    restart: always

volumes:
  public:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./public/

networks:
  one:
    driver: bridge
