# services:
#   frontend:
#     build: ./
#     ports:
#       - "8080:80"
#     restart: always
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
services:
  frontend:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - .:/app
      - /app/node_modules
      - ../shared/certs:/app/certs:ro
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/7000"]
      interval: 30s
      timeout: 10s
      retries: 3
