FROM node:22-alpine

WORKDIR /app

EXPOSE 8081

CMD ["npm", "run", "dev"]

COPY package.json package-lock.json  ./

RUN npm install
# RUN npm ci

COPY tsconfig.json vite.config.ts esbuild.config.js ./

COPY public ./public

COPY src ./src
