input {
  beats {
	id => "filebeat input"
    port => 5044
	# ssl => true
	# ssl_certificate => "certs/logstash.crt"
	# ssl_key => "certs/logstash.key"
  }
}

# filter {

#   if [message] =~ "^{.*}$" {
#     json {
#       source => "message"
# 	  skip_on_invalid_json => true
#     }
#   }
# }


filter {
	if [message] =~ "^{.*}$" {
  		json {
			skip_on_invalid_json => true
			source => "message"
			target => "parsed_json"
			remove_field => ["message"]
		}

		mutate {
			rename => { "[docker][container][name]" => "container_name" }
			rename => { "[docker][container][id]" => "container_id" }
			# rename => { "parsed_json" => "test" }
			remove_field => ["beat", "host", "@version"]
		}

		date {
			match => ["parsed_json.timestamp", "ISO8601"]
			target => "@timestamp"
		}
	}
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
	ecs_compatibility => v8
    index => "logs-%{+YYYY.MM.dd}"
  }
  
#   stdout { codec => rubydebug }
}