input {
  beats {
	id => "filebeat input"
    port => 5044
	# ssl => true
	# ssl_certificate => "certs/logstash.crt"
	# ssl_key => "certs/logstash.key"
  }
}

# filter {

#   if [message] =~ "^{.*}$" {
#     json {
#       source => "message"
# 	  skip_on_invalid_json => true
#     }
#   }
# }


filter {
  if [message] =~ "^{.*}$" {
	json {
	  source => "message"
	  target => "json"
	  skip_on_invalid_json => true
	}
  }

#   mutate {
#     add_field => { "custom_container_name" => "%{[docker][container][name]}" }
#   }

}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
	ecs_compatibility => v8
    index => "logs-%{+YYYY.MM.dd}"
  }
  
#   stdout { codec => rubydebug }
}