services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  notifications-manager:
    build:
      context: ./notifications-manager
    volumes:
      - ./notifications-manager/src:/app/src
      - ./notifications-manager/package.json:/app/package.json
      - ./notifications-manager/.env.example:/app/.env
    depends_on:
      - nats
    command: npm run dev
    environment:
      - NATS_URL=nats://nats:4222
      - PORT=7001
    ports:
      - "7001:7001"