services:
  nats_game:
    image: nats:latest
    container_name: nats_game
    ports:
      - "4222:4222"

  lobby-manager:
    container_name: lobby_manager
    build:
      context: ./services/game/lobby-manager
    volumes:
      - ./services/game/lobby-manager/src:/app/src
      # - ./lobby-manager/test:/app/test
      - ./services/game/lobby-manager/package.json:/app/package.json
      - ./services/game/lobby-manager/.env.example:/app/.env
      - ./shared/certs:/usr/src/app/certs:ro
    depends_on:
      - nats_game
    command: npm run dev
    environment:
      - NATS_URL=nats://nats_game:4222
      - PORT=5001
    ports:
      - "5001:5001"
      - "5011:5011"

  game-manager:
    container_name: game_manager
    build: ./services/game/game-manager
    volumes:
      - ./services/game/game-manager/src:/app/src
      - ./services/game/game-manager/test:/app/test
      - ./services/game/game-manager/package.json:/app/package.json
      - ./services/game/game-manager/.env.example:/app/.env
    command: npm run dev
    restart: unless-stopped
    environment:
      - SERVICE_NAME=game-manager
      - NATS_URL=nats://nats_game:4222
      - PORT=5003
    depends_on:
      - nats_game
    ports:
      - "5003:5003"
      - "5050:5050" # For metrics

  user-interface:
    container_name: user_interface
    build: ./services/game/user-interface
    volumes:
      - ./services/game/user-interface/src:/app/src
      - ./services/game/user-interface/test:/app/test
      - ./services/game/user-interface/package.json:/app/package.json
      - ./services/game/user-interface/.env.example:/app/.env
      - ./shared/certs:/app/certs:ro
    command: npm run start
    ports:
    - "5004:5004"
    - "5051:5051" # For metrics
    restart: unless-stopped
    environment:
      - SERVICE_NAME=user-interface
      - NATS_URL=nats://nats_game:4222
    depends_on:
      - nats_game

  pong-physics:
    container_name: pong_physics
    build: ./services/game/pong-physics
    volumes:
      - ./services/game/pong-physics/src:/app/src
      - ./services/game/pong-physics/test:/app/test
      - ./services/game/pong-physics/package.json:/app/package.json
      - ./services/game/pong-physics/.env.example:/app/.env
    command: npm run dev
    restart: unless-stopped
    environment:
      - SERVICE_NAME=pong-physics
      - NATS_URL=nats://nats_game:4222
    depends_on:
      - nats_game

  pongbr-physics:
    container_name: pongBR_physics
    build: ./services/game/pongBR-physics
    volumes:
      # - ./profiler-logs:/app/profiler-logs
      - ./services/game/pongBR-physics/src:/app/src
      - ./services/game/pongBR-physics/test:/app/test
      - ./services/game/pongBR-physics/package.json:/app/package.json
      - ./services/game/pongBR-physics/.env.example:/app/.env
    command: npm run dev
    # ports:
    # - "9229:9229"
    restart: unless-stopped
    environment:
      - SERVICE_NAME=pongBR-physics
      - NATS_URL=nats://nats_game:4222
    depends_on:
      - nats_game

  # pongio-physics:
  #   build: ./services/game/pongIO-physics
  #   volumes:
  #     - ./services/game/pongIO-physics/src:/app/src
  #     - ./services/game/pongIO-physics/test:/app/test
  #     - ./services/game/pongIO-physics/package.json:/app/package.json
  #     - ./services/game/pongIO-physics/.env.example:/app/.env
  #   command: npm run dev
  #   restart: unless-stopped
  #   environment:
  #     - SERVICE_NAME=pongIO-physics
  #     - NATS_URL=nats://nats:4222
  #   depends_on:
  #     - nats

  ai:
    container_name: ai_service
    build: ./services/game/ai
    volumes:
      - ./services/game/ai/src:/app/src
      - ./services/game/ai/test:/app/test
      - ./services/game/ai/package.json:/app/package.json
      - ./services/game/ai/.env.example:/app/.env
    command: npm run dev
    restart: unless-stopped
    environment:
      - SERVICE_NAME=ai
      - NATS_URL=nats://nats_game:4222
    depends_on:
      - nats_game
