# FROM node:18
#
# WORKDIR /app
#
# COPY package.json tsconfig.json vite.config.ts  ./
# COPY src ./src
#
# RUN npm install
#
# EXPOSE 5173
#
# CMD ["npm", "run", "dev"]
#
FROM node:18

WORKDIR /app

# Copy dependency files and install them. This maximizes Docker cache reuse.
COPY package*.json ./
RUN npm install

# Copy all source files
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]

