global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'register'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/register/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true
  - job_name: 'auth'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/auth/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true
  - job_name: 'stats'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/stats/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true
  - job_name: 'friends'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/friends/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true
  - job_name: 'get-info'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/info/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true
  - job_name: 'update-info'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/update-info/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true