services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "6002:6002"
    networks:
      - transcendence-network
  
  statsManager:
    build: 
      context: ./services/stats/statsManager
    container_name: statsManager
    ports:
      - "6000:6000"
    volumes:
      - certs:/app/certs:ro
      - shared:/app/shared
    environment:
      - NODE_ENV=development
      - SSL_KEY=${SSL_KEY}
      - SSL_CERT=${SSL_CERT}
      - API_GATEWAY_KEY=${API_GATEWAY_KEY}
      - NATS_URL=${NATS_URL}
    networks:
      - transcendence-network

  statsDatabase:
    build: 
      context: ./services/stats/stats_database
    container_name: stats_database
    volumes:
      - ./shared/db:/app/data
      - ./shared/certs:/app/certs:ro
      - shared:/app/shared
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - NATS_URL=${NATS_URL}
    networks:
      - transcendence-network
    depends_on:
      database_certs-init:
        condition: service_completed_successfully

volumes:
  shared:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./shared
  