CREATE TABLE IF NOT EXISTS match (
	match_id INTEGER PRIMARY KEY AUTOINCREMENT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	game_mode TEXT NOT NULL,
	winner_id INTEGER NOT NULL,
	total_players INTEGER NOT NULL,
	FOREIGN KEY (winner_id) REFERENCES users(id) ON DELETE CASCADE
);