
services:
  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      # - /home/efayolle/Documents/Transcendence/Transcendence/elk/elasticsearch/data:/usr/share/elasticsearch/data
      # - /home/efayolle/Documents/Transcendence/Transcendence/elk/elasticsearch/logs:/usr/share/elasticsearch/logs
      - /home/efayolle/Documents/Transcendence/Transcendence/elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      - logging

  logstash:
    image: logstash:8.6.2
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - /home/efayolle/Documents/Transcendence/Transcendence/elk/logstash/pipeline:/usr/share/logstash/pipeline
      - /home/efayolle/Documents/Transcendence/Transcendence/elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      # - /home/efayolle/goinfre/docker/containers:/var/lib/docker/containers:ro
      # - ${42_PATH}elk/logstash/logs:/usr/share/logstash/logs
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - logging
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.6.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - /home/efayolle/Documents/Transcendence/Transcendence/elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      # - ${42_PATH}elk/kibana/logs:/usr/share/kibana/logs
    ports:
      - "5601:5601"
    networks:
      - logging
    depends_on:
      - elasticsearch
      - logstash

  filebeat:
    image: elastic/filebeat:8.6.2
    container_name: filebeat
    volumes:
      - /home/efayolle/Documents/Transcendence/Transcendence/elk/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      # - ${42_PATH}elk/filebeat/logs:/usr/share/filebeat/logs
      - /home/efayolle/goinfre/docker/containers:/var/lib/docker/containers:ro
      # - /var/run:/var/run
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - logging
    depends_on:
      - logstash
    user: root

networks:
  logging:
    driver: bridge