const statusCode = {
	SUCCESS: 200,
	CREATED: 201,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	NOT_FOUND: 404,
	CONFLICT: 409,
	INTERNAL_SERVER_ERROR: 500,
};

const returnMessages = {
	UNAUTHORIZED: 'Unauthorized',
	INTERNAL_SERVER_ERROR: 'Internal server error',
	FRIENDSHIP_NOT_FOUND: 'Friendship not found',
	FRIEND_REQUEST_NOT_FOUND: 'Friend request not found',
	FRIEND_REQUEST_SENT: 'Friend request sent',
	FRIEND_REQUEST_ACCEPTED: 'Friend request accepted',
	FRIEND_REQUEST_DECLINED: 'Friend request declined',
	AUTO_FRIEND_REQUEST: 'You cannot add yourself as a friend',
	AUTO_DELETE_REQUEST: 'You cannot delete yourself as a friend',
	AUTO_DECLINE_REQUEST: 'You cannot decline yourself as a friend',
	AUTO_BLOCK_REQUEST: 'You cannot block yourself',
	AUTO_UNBLOCK_REQUEST: 'You cannot unblock yourself',
	FRIEND_DELETED: 'Friendship deleted',
	ALREADY_FRIEND: 'You are already friends with this user',
	ALREADY_FRIEND_REQUEST: 'Friend request already sent',
	ALREADY_RECEIVED: 'This user has already sent you a friend request',
	ALREADY_BLOCKED: 'You have already blocked this user',
	USER_BLOCKED_YOU: 'This user has blocked you',
	NOT_BLOCKED: 'You cannot unblock a user that you have not blocked',
	ADD_BLOCKED_USER: 'You cannot add a blocked user as a friend',
	NO_BLOCKED_USERS: 'You have no blocked users',
	FRIENDLIST_NOT_FOUND: 'Friendlist is empty',
	SELF_RESEARCH: 'You cannot search for yourself',
	USER_NOT_FOUND: 'User not found',
	USERNAME_ALREADY_USED: 'Username is already in use',
	USERNAME_PASSWORD_REQUIRED: 'Username and password are required',
	USERNAME_REQUIRED: 'Player username is required',
	PASSWORD_REQUIRED: 'Password is required',
	NEW_PASSWORD_REQUIRED: 'New password is required',
	AVATAR_REQUIRED: 'No avatar file provided',
	UUID_REQUIRED: 'UUID is required',
	PASSWORD_INVALID: 'Password must be at least 8 characters long, contain at least one uppercase letter, one lowercase letter, and one number',
	USERNAME_INVALID: 'Username must be between 3 and 20 characters without any special characters',
	INVALID_AVATAR_URL: 'Invalid avatar URL',
	INVALID_TYPE: 'Invalid image type',
	INVALID_SEARCH_TYPE: 'Invalid search type',
	INVALID_TOKEN: 'Invalid token',
	INVALID_CODE: 'Invalid code',
	USERNAME_UPDATED: 'User info updated',
	PASSWORD_UPDATED: 'Password updated successfully',
	AVATAR_UPDATED: 'Avatar updated successfully',
	USER_BLOCKED: 'User blocked',
	USER_BLOCKED_SUCCESS: 'User blocked successfully',
	USER_UNBLOCKED: 'User unblocked successfully',
	NOTHING_TO_UPDATE: 'Nothing to update',
	BAD_PASSWORD: 'Invalid password',
	MISSING_TOKEN: 'Token is required',
	TWO_FA_ALREADY_ENABLED: '2FA is already enabled',
	TWO_FA_ENABLED: '2FA is enabled',
	TWO_FA_NOT_ENABLED: '2FA is not enabled',
	TWO_FA_VERIFIED: '2FA verified',
	TWO_FA_DISABLED: '2FA disabled',
	LOGGED_IN: 'Logged in successfully',
	GOOGLE_LOGGED_IN: 'Logged in with Google successfully',
	GOOGLE_CREATED_LOGGED_IN: 'Registered and logged in with Google successfully',
	LOGGED_OUT: 'Logged out successfully',
	USER_CREATED: 'User registered successfully',
	INTRA42_LOGGED_IN: 'Logged in with Intra42 successfully',
	CANT_ENABLE_2FA: 'You cannot enable 2FA for this account',
	PLAYER_INACTIVE: 'Player not in a lobby or a game',
	STATUS_ALREADY_EXISTS: 'Status already exists for this user',
	INVALID_STATUS: 'Invalid status value',
	STATUS_ADDED: 'Status added successfully',
	STATUS_UPDATED: 'Status updated successfully',
	STATUS_NOT_FOUND: 'Status not found for this user',
	BAD_GAME_ID: 'Invalid game or lobby ID',
	IDENTIFIER_TYPE_REQUIRED: 'Identifier and type are required',
	PROVIDER_PASSWORD_CONFLICT: 'You cannot connect with a password for this account',
	UNKNOWN_42_API_URI: 'Unknown uri from 42 API',
};

const statusReturn = { 
	STATUS_001: { http: 400, code: 4001, message: returnMessages.PLAYER_INACTIVE },
	STATUS_002: { http: 409, code: 4091, message: returnMessages.STATUS_ALREADY_EXISTS },
	STATUS_003: { http: 400, code: 4002, message: returnMessages.INVALID_STATUS },
	STATUS_004: { http: 201, code: 2011, message: returnMessages.STATUS_ADDED },
	STATUS_005: { http: 200, code: 2001, message: returnMessages.STATUS_UPDATED },
	STATUS_006: { http: 404, code: 4041, message: returnMessages.STATUS_NOT_FOUND },
	STATUS_007: { http: 400, code: 4003, message: returnMessages.BAD_GAME_ID },
}

const userReturn = { 
	USER_001: { http: 404, code: 4042, message: returnMessages.USER_NOT_FOUND },
	USER_002: { http: 409, code: 4092, message: returnMessages.USERNAME_ALREADY_USED },
	USER_003: { http: 400, code: 4004, message: returnMessages.USERNAME_PASSWORD_REQUIRED },
	USER_004: { http: 400, code: 4005, message: returnMessages.USERNAME_REQUIRED },
	USER_005: { http: 400, code: 4006, message: returnMessages.PASSWORD_REQUIRED },
	USER_006: { http: 400, code: 4007, message: returnMessages.NEW_PASSWORD_REQUIRED },
	USER_007: { http: 400, code: 4008, message: returnMessages.AVATAR_REQUIRED },
	USER_008: { http: 400, code: 4009, message: returnMessages.UUID_REQUIRED },
	USER_009: { http: 400, code: 40010, message: returnMessages.PASSWORD_INVALID },
	USER_010: { http: 400, code: 40011, message: returnMessages.USERNAME_INVALID },
	USER_011: { http: 400, code: 40012, message: returnMessages.INVALID_AVATAR_URL },
	USER_012: { http: 400, code: 40013, message: returnMessages.INVALID_TYPE },
	USER_013: { http: 400, code: 40014, message: returnMessages.INVALID_TOKEN },
	USER_014: { http: 400, code: 40015, message: returnMessages.INVALID_CODE },
	USER_015: { http: 200, code: 2002, message: returnMessages.USERNAME_UPDATED },
	USER_016: { http: 200, code: 2003, message: returnMessages.PASSWORD_UPDATED },
	USER_017: { http: 200, code: 2004, message: returnMessages.AVATAR_UPDATED },
	USER_018: { http: 400, code: 40016, message: returnMessages.USER_BLOCKED },
	USER_019: { http: 200, code: 2005, message: returnMessages.USER_BLOCKED_SUCCESS },
	USER_020: { http: 200, code: 2006, message: returnMessages.USER_UNBLOCKED },
	USER_021: { http: 400, code: 40017, message: returnMessages.NOTHING_TO_UPDATE },
	USER_022: { http: 401, code: 4011, message: returnMessages.BAD_PASSWORD },
	USER_023: { http: 400, code: 40018, message: returnMessages.MISSING_TOKEN },
	USER_024: { http: 409, code: 4093, message: returnMessages.TWO_FA_ALREADY_ENABLED },
	USER_025: { http: 200, code: 2007, message: returnMessages.TWO_FA_ENABLED },
	USER_026: { http: 400, code: 40019, message: returnMessages.TWO_FA_NOT_ENABLED },
	USER_027: { http: 200, code: 2008, message: returnMessages.TWO_FA_VERIFIED },
	USER_028: { http: 200, code: 2009, message: returnMessages.TWO_FA_DISABLED },
	USER_029: { http: 400, code: 40020, message: returnMessages.CANT_ENABLE_2FA },
	USER_030: { http: 200, code: 20010, message: returnMessages.GOOGLE_LOGGED_IN },
	USER_031: { http: 201, code: 2012, message: returnMessages.GOOGLE_CREATED_LOGGED_IN },
	USER_032: { http: 200, code: 20011, message: returnMessages.LOGGED_OUT },
	USER_033: { http: 201, code: 2013, message: returnMessages.USER_CREATED },
	USER_034: { http: 200, code: 20012, message: returnMessages.INTRA42_LOGGED_IN },
	USER_035: { http: 200, code: 20013, message: returnMessages.LOGGED_IN },
	USER_036: { http: 400, code: 40031, message: returnMessages.IDENTIFIER_TYPE_REQUIRED },
	USER_037: { http: 400, code: 40032, message: returnMessages.INVALID_SEARCH_TYPE },
	USER_038: { http: 400, code: 40033, message: returnMessages.PROVIDER_PASSWORD_CONFLICT },
	USER_039: { http: 401, code: 40139, message: returnMessages.UNKNOWN_42_API_URI },
};

const friendshipReturn = {
	FRIEND_001: { http: 404, code: 4043, message: returnMessages.FRIENDSHIP_NOT_FOUND },
	FRIEND_002: { http: 404, code: 4044, message: returnMessages.FRIEND_REQUEST_NOT_FOUND },
	FRIEND_003: { http: 200, code: 20014, message: returnMessages.FRIEND_REQUEST_SENT },
	FRIEND_004: { http: 200, code: 20015, message: returnMessages.FRIEND_REQUEST_ACCEPTED },
	FRIEND_005: { http: 200, code: 20016, message: returnMessages.FRIEND_REQUEST_DECLINED },
	FRIEND_006: { http: 400, code: 40021, message: returnMessages.AUTO_FRIEND_REQUEST },
	FRIEND_007: { http: 400, code: 40022, message: returnMessages.AUTO_DELETE_REQUEST },
	FRIEND_008: { http: 400, code: 40023, message: returnMessages.AUTO_DECLINE_REQUEST },
	FRIEND_009: { http: 400, code: 40024, message: returnMessages.AUTO_BLOCK_REQUEST },
	FRIEND_010: { http: 400, code: 40025, message: returnMessages.AUTO_UNBLOCK_REQUEST },
	FRIEND_011: { http: 200, code: 20017, message: returnMessages.FRIEND_DELETED },
	FRIEND_012: { http: 409, code: 4094, message: returnMessages.ALREADY_FRIEND },
	FRIEND_013: { http: 409, code: 4095, message: returnMessages.ALREADY_FRIEND_REQUEST },
	FRIEND_014: { http: 409, code: 4096, message: returnMessages.ALREADY_RECEIVED },
	FRIEND_015: { http: 409, code: 4097, message: returnMessages.ALREADY_BLOCKED },
	FRIEND_016: { http: 400, code: 40026, message: returnMessages.USER_BLOCKED_YOU },
	FRIEND_017: { http: 400, code: 40027, message: returnMessages.NOT_BLOCKED },
	FRIEND_018: { http: 400, code: 40028, message: returnMessages.ADD_BLOCKED_USER },
	FRIEND_019: { http: 404, code: 4045, message: returnMessages.NO_BLOCKED_USERS },
	FRIEND_020: { http: 404, code: 4046, message: returnMessages.FRIENDLIST_NOT_FOUND },
	FRIEND_021: { http: 400, code: 40029, message: returnMessages.SELF_RESEARCH }
};

const statsReturn = {
	STATS_001: { http: 400, code: 40030, message: 'Invalid game mode' }
};

export { statusCode, returnMessages, friendshipReturn, userReturn, statusReturn, statsReturn };