services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./metrics/prometheus/web-config.yml:/etc/prometheus/web-config.yml
      - ./shared/certs:/etc/prometheus/certs:ro
    ports:
      - "3003:3003"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web-config.yml'
      - '--web.listen-address=:3003'
      - '--web.enable-lifecycle'
    depends_on:
      database_certs-init:
        condition: service_completed_successfully
    networks:
      - transcendence-network
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3004:3004"
    volumes:
      - ./metrics/grafana:/var/lib/grafana
      - ./metrics/grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - ./shared/certs:/etc/grafana/certs:ro

    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    user: "0"
    depends_on:
      prometheus:
        condition: service_started
    networks:
      - transcendence-network

